spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
# Logger Config
logging:
  level:
    com.hornyun.blog.mapper: debug