spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:/db/liquibase/changelog/changelog.sql
    enabled: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
# Logger Config
logging:
  level:
    root: warn
  file:
    name: /Users/hornyun/IdeaProjects/blog/log/error.log


debug: true
server:
  servlet:
    context-path: /blog